const authenticated = async (req, res, next) => {
  try {
  } catch (error) {}
};
